---
title: "KI in der Lehre: Impuls"
format:
  html:
    toc: false
about:
  template: marquee
  links:
    - icon: inbox-fill
      text: Email
      href: mailto:virtuelle.akademie@bfh.ch
    - icon: magic
      text: Virtuelle Akademie
      href: https://virtuelleakademie.ch/
    - icon: lightbulb-fill
      text: Knowledge Base
      href: https://virtuelleakademie.ch/knowledge-base/
    - icon: github
      text: GitHub
      href: https://github.com/virtuelleakademie/ki-lehre-impuls/
---

## Präsentation

Input (30 Min).

{{< revealjs file="slides/index.html" height="500px" class="ratio ratio-16x9" >}}

Nutze die Pfeiltasten oder die Leertaste um durch die Präsentation zu navigieren. Drücke `F` für Vollbild.


### Weiterbildungsangebot

Dieser Impuls bietet einen kompakten Überblick über den aktuellen Forschungsstand und die lernwissenschaftlichen Grundlagen. Die Virtuelle Akademie der BFH bietet im Rahmen des [Weiterebildungsprogramms](https://www.bfh.ch/de/ueber-die-bfh/service-beratung/virtuelle-akademie/#weiterbildungsangebote) drei aufbauende Kurse an, die diese Themen vertiefen:

[KI in der Lehre: Einführung](https://virtuelleakademie.github.io/ki-lehre-beginner/): Grundlagen zu Sprachmodellen und Chatbots.

[KI in der Lehre: Lernen mit KI verstehen](https://virtuelleakademie.github.io/ki-lehre-intermediate/): Lernpsychologie und KI-gestütztes Lerndesign.

[KI in der Lehre: Lerntools bauen](https://virtuelleakademie.github.io/ki-lehre-advanced/): Workshop zur Entwicklung eines eigenen KI-gestützten Lerntools.

Aussderdem bieten wir ein [Zertifikat (7 ECTS)](https://www.bfh.ch/de/weiterbildung/kurse/zertifikatskurs-hochschuldidaktik/) und einen [CAS (10 ECTS)](https://www.bfh.ch/de/weiterbildung/cas/hochschuldidaktik/) in Hochschuldidaktik an, der unter anderem diese Themen aufgreift. 

## Kontakt

[Dr. Andrew Ellis](mailto:andrew.ellis@bfh.ch) ist Kognitionspsychologe und Wissenschaftlicher Mitarbeiter an der [Virtuellen Akademie](https://virtuelleakademie.ch/) der Berner Fachhochschule. 

[Dr. Raphael Schween](mailto:raphael.schween@bfh.ch) ist Wissenschaftler mit Schwerpunkten in (Bewegungs-)Lernen und kognitiver Modellierung und Experte für KI an der [Virtuellen Akademie](https://virtuelleakademie.ch/) der Berner Fachhochschule.
 
Sie erforschen, wie künstliche Intelligenz in Bildungssystemen wirkungsvoll eingesetzt werden kann.